### PR TITLE
[FIXED] image name

### PR DESCRIPTION
**Pull request by AbreuY**
Fixed image name as it gives a 404 error and the image is not displayed correctly in the README file.

### CODE REVIEW

**Review by ATechAjay — COMMENTED** [review]
You can write simple text instead of an image:)

**Comment by AbreuY** [comment]
> You can write simple text instead of an image:)

Hi, I'm sorry. I didn't understand what you mean.

**Comment by Angra974** [comment]
> > You can write simple text instead of an image:)
> 
> Hi, I'm sorry. I didn't understand what you mean.

It's an error from me ^^ it's the reason why he didn't notice it and he didn't figure out what you're pointing at. 
Thanks from the correction :)

**Comment by Angra974** [comment]
Ajay
the oneMoreThing.png used in the readme.MD file for the whole project needs to be corrected.
One starts with lowercase and the second start with an uppercase.
As it's not a problem to get the image to be shown in localhost ( windows ) but
it didn't appear correctly on GitHub due to the difference.

**Pull request closed without merging**
